name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:

      # Header
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 8damon
          template: classic
          base: header
          config_timezone: Asia/Dubai

          output_action: commit
          committer_branch: generated
          filename: metrics.header.svg

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 8damon
          template: classic
          base: ""
          config_timezone: Asia/Dubai

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_other: false
          plugin_languages_categories: programming, markup
          plugin_languages_ignored: html, css

          output_action: commit
          committer_branch: generated
          filename: metrics.languages.svg
