name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 8damon
          template: classic
          base: header
          config_timezone: Asia/Dubai

          output_action: commit
          committer_branch: generated
          filename: metrics.header.svg
          
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 8damon
          template: classic
          base: ""
          config_timezone: Asia/Dubai

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_threshold: 2%
          plugin_languages_other: yes
          plugin_languages_categories: programming, markup
          plugin_languages_ignored: html, css

          commits_authoring: 8damon, 8damon@users.noreply.github.com

          output_action: commit
          committer_branch: generated
          filename: metrics.languages.svg

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 8damon
          template: classic
          base: ""
          config_timezone: Asia/Dubai

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request
          plugin_notable_filter: stars:>25 forks:>5
          plugin_notable_repositories: yes

          output_action: commit
          committer_branch: generated
          filename: metrics.notable.svg
